# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6837596cfb06c33f8f6dd02c8728363b7e241ea164974eebadf499e6a56a9abd6a3933f8f145d0f9d4407d4d05aa4aa991a2f0c275e33f4c94002956a0bd1f77

test:
  secret_key_base: 091c7c4358c7c25eaaf3f439afb0054aba9fa4f718b728ac003142766e19261dc6a7bc38ac71755ab5d1d0a6ad231e97d53b279c91054e8c46d617e1e64c9b7c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
